[workspace]
resolver = "3"

members = ["spinlock", "kernel", "arrayvec"]
default-members = ["kernel"]

[profile.release]
lto = true
opt-level = 3
panic = "abort"
debug = "none"

[profile.dev]
debug = "full"
